/****************************************
 Generated by Actando JS Generator
 File : config.js
 (c) 2014 Actando
****************************************/
var SlideShow_ConfigRes = $.inherit({
xmlslideshow:"res/config.xml",
isstandalone:true,
debug:false,
jscom:"SS_COM_PHARMACADEMY"
});